spring:
  application:
      name: api-gateway
  output:
    ansi:
      enabled: ALWAYS

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://user-service:8081/
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1